name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare for deployment (copy all project files)
        run: |
          # Simple approach: copy EVERYTHING to dist except node_modules and dist itself
          find . -type f -not -path "./node_modules/*" -not -path "./dist/*" -not -path "./.git/*" -exec cp --parents {} dist/ \;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
